# Generated by Django 4.1.3 on 2022-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docsrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('OrganisationName', models.CharField(max_length=120)),
                ('Hospitalname', models.CharField(max_length=120)),
                ('OrganisationType', models.CharField(choices=[('hospital', 'HOSPITAL'), ('pharmacy', 'PHARMACY'), ('insurance company', 'INSURANCE COMPANY')], default='hospital', max_length=20)),
                ('DocsType', models.CharField(max_length=15)),
                ('Docs', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=120)),
                ('ConfirmPassword', models.CharField(max_length=120)),
                ('Organisationlisence', models.ImageField(upload_to='')),
                ('OrganisationType', models.CharField(choices=[('hospital', 'HOSPITAL'), ('pharmacy', 'PHARMACY'), ('insurance company', 'INSURANCE COMPANY')], default='hospital', max_length=20)),
                ('City', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=150, null=True)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=120)),
                ('ConfirmPassword', models.CharField(max_length=120)),
                ('Phone', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=120)),
                ('Bloodtype', models.CharField(max_length=3, null=True)),
                ('PatientidType', models.CharField(choices=[('Adhaar', 'ADHAAR'), ('Driving license', 'DRIVING LICENSE'), ('Voterid', 'VOTERID')], default='Aadhar', max_length=20)),
                ('Patientid', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, null=True)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=150)),
                ('Password', models.CharField(max_length=120)),
                ('ConfirmPassword', models.CharField(max_length=120)),
                ('Role', models.CharField(max_length=120)),
                ('Hospital_Name', models.CharField(max_length=120)),
                ('City', models.CharField(max_length=120)),
                ('Professionalid', models.ImageField(upload_to='')),
            ],
        ),
    ]
