# Generated by Django 4.1.3 on 2022-11-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientidType',
            field=models.CharField(choices=[('Adhaar', 'ADHAAR'), ('Driving license', 'DRIVING LICENSE'), ('Voterid', 'VOTERID')], default='Aadhar', max_length=20, null=True),
        ),
    ]
