# Generated by Django 4.1.3 on 2022-11-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_patient_id_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Verified',
            field=models.BooleanField(default='False'),
        ),
    ]
