# Generated by Django 4.1.3 on 2022-11-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_patient_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AddField(
            model_name='organisation',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='Email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
