# Generated by Django 4.1.3 on 2022-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_organisation_id_organisation_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='id',
        ),
        migrations.AlterField(
            model_name='professional',
            name='Email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
