# Generated by Django 4.1.3 on 2022-11-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_professional_id_alter_professional_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='Verified',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='professional',
            name='Verified',
            field=models.BooleanField(default='False'),
        ),
    ]
